Repository pawap90/uade-movie-app, pull requests merged in 2020-06, with the labels that each got.

#10 fix error getting upcoming series
  src/screens/HomeScreen.js
  src/services/MovieDbService.js
Labels: bug

#20 Backend service
  README.md
  package-lock.json
  package.json
  src/Constants.js
  src/errors/ErrorHandler.js
  src/errors/UserError.js
  src/models/AccountModel.js
  src/models/LoginModel.js
  src/services/AccountService.js
Labels: feature

#19 Setup tab bar navigation
  App.js
  assets/home.png
  assets/list.png
  assets/user.png
  package-lock.json
  package.json
  src/BaseStyles.js
  src/navigation/TabBarNavigation.js
  src/screens/MyListsScreen.js
  src/screens/ProfileScreen.js
Labels: feature

#21 Ft/profile
  assets/ic_key.png
  assets/key.png
  src/components/ProfileAttribute.js
  src/components/ProfileGenres.js
  src/components/ProfileSection.js
  src/components/Separator.js
  src/components/Tag.js
  src/navigation/TabBarNavigation.js
  src/screens/GenreSelectionScreen.js
  src/screens/ProfileScreen.js
Labels: feature

#45 25 update profile - improvements
  src/components/ProfileAttribute.js
  src/screens/GenreSelectionScreen.js
  src/screens/ProfileScreen.js
Labels: enhancement

#44 43 create list
  src/models/ListModel.js
  src/navigation/TabBarNavigation.js
  src/screens/ListCreateScreen.js
  src/screens/ListsScreen.js
  src/services/ListService.js
Labels: feature

#46 Share media items across apps
  assets/share.png
  src/components/MovieHeader.js
  src/components/ShareMediaItemButton.js
  src/models/MediaModel.js
  src/screens/MediaDetailsScreen.js
  src/services/MovieDbService.js
Labels: feature

#47 Remove buttons from home
  src/screens/HomeScreen.js
Labels: enhancement
